require 'rubygems'
require 'rake'
require 'echoe'

Echoe.new('robot_remote_server') do |p|
  p.description    = "Remote server for Robot Framework in Ruby"
  p.url            = "http://github.com/semperos/robot-remote-server"
  p.author         = "Daniel Gregoire"
  p.ignore_pattern = ["tmp/*", "script/*"]
  p.development_dependencies = []
end
